### ISSUE TITLE
Tuist 구성

### ISSUE THREAD

**Issue by sudopark** [sudopark/TodoCalendar#146]
초기에 했어야하는데..
있으면 정말 좋을거겉다 이말이야..

**Comment by lavaKangJun** [comment]
외부 디펜던시 관리 방법
1. SPM 직접 사용
2. Tuist의 Dependencies.swift 를 사용한 Swift Package 의존성 관리 방법

최초 설정은 2번으로 했으나 메인 플젝에서 하위 모듈에서 사용하는 외부 모듈들을 다 의존하는 이슈가 있어서 1번으로 변경함.
1번 방식으로 사용하면 Tuist/Dependencies.swift 사용안함

<img width="1110" alt="스크린샷 2023-12-20 오후 11 49 42" src="https://github.com/sudopark/TodoCalendar/assets/37703727/ee92d7e8-5344-47ff-80c5-ae15d5aab55e">


참고
https://okanghoon.medium.com/tuist-%EB%A1%9C-%EC%99%B8%EB%B6%80-%EC%9D%98%EC%A1%B4%EC%84%B1-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0-85609e70133c

**Comment by lavaKangJun** [comment]
1. 기존에 플젝이 구성되어 있는 경우에 Tuist 적용하기
- 기존 플젝 이름과 동일한 폴더를 하나 만들고 아무것도 없는 그 폴더 하위에서  
`tuist init --platform ios`  를 통해 플젝 구성에 필요한 파일들을 생성한다.

그럼 아래와 같이 파일들이 생성됨
<img width="200" alt="스크린샷 2023-12-28 오전 12 06 32" src="https://github.com/sudopark/TodoCalendar/assets/37703727/1a095482-7373-4a18-bfb3-e5be35a6e110">
